version: '3.8'
services:
  hotel-service:
    build:
      context: .
      dockerfile: src/HotelService/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__HotelDb: Host=hotel-db;Database=HotelService;Username=postgres;Password=postgres
      Serilog__WriteTo__1__Args__nodeUris: http://elasticsearch:9200
    depends_on:
      - hotel-db
      - elasticsearch
      - rabbitmq
    networks:
      - hotel_network

  report-service:
    build:
      context: .
      dockerfile: src/ReportService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__HotelDb: Host=hotel-db;Database=HotelService;Username=postgres;Password=postgres
      Serilog__WriteTo__1__Args__nodeUris: http://elasticsearch:9200
    depends_on:
      - hotel-db
      - elasticsearch
      - rabbitmq
      - hotel-service
    networks:
      - hotel_network

  hotel-db:
    image: postgres:15
    container_name: hotel-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: HotelService
    ports:
      - "5432:5432"
    volumes:
      - hotel-db-data:/var/lib/postgresql/data
    networks:
      - hotel_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    networks:
      - hotel_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - hotel_network

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - hotel_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  hotel_network:
    driver: bridge

volumes:
  hotel-db-data:
  rabbitmq_data:
